export ARCH=x86_64
PREFIX=
KERNELDIR=/lib/modules/5.6.19/build
KERNELSOURCEDIR=
KERNELVERSION=5.6.19
export CROSS_COMPILE=
export CC=gcc
export LD=ld
export OBJCOPY=objcopy
export AR=ar
KVM_VERSION=kvm-devel
